Exception Handling
==================

.. post:: 30/12/2020
   :tags: csharp

Async functions
---------------

When using `await` the first exception is bubbled up.

When using `.Result` the `AggregateException` is thrown.
