Exception Handling
==================

.. post:: Dec 30, 2020
   :tags: csharp

Async functions
---------------

When using `await` the first exception is bubbled up.

When using `.Result` the `AggregateException` is thrown.
